In [1]:
import tensorflow as tf

In [20]:
#initilization of tensors
#tensors are just n dimensional blocks of data, which are the basis of all machine learning and deep learning operations

x=tf.constant(4,shape=(1,1),dtype=tf.float32)
print(x)

y=tf.constant([[1,2,3],[4,5,6]])
print(y)

#can also use the zeros function below
z=tf.ones((3,3))
print(z)

#I for the identity matrix
a=tf.eye(3)
print(a)

#can also take stuff from distributions

x=tf.random.normal((3,3),mean=0,stddev=1)
print(x)

x=tf.random.uniform((1,3),minval=0,maxval=1)
print(x)

#tf.range function
# can use tf.cast to convert datatypes


#Mathematical Operations:

x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
z=tf.add(x,y) # or z=x+y
print(z)
b=tf.subtract(x,y)
c=tf.multiply(x,y)
d=tf.tensordot(x,y,axes=1)
print(d)
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
result=tf.matmul(x,y)
print(result)



tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.59324175 -2.9224243   0.00407465]
 [-1.1086311  -0.03067601  0.22614753]
 [ 0.9201103   0.2679541  -0.08159841]], shape=(3, 3), dtype=float32)
tf.Tensor([[0.1270256 0.7915137 0.9790832]], shape=(1, 3), dtype=float32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(
[[-3.5250335  -2.7617478   0.2763046   3.119842  ]
 [ 1.5462599   0.6663332   2.8277748  -0.03867079]], shape=(2, 4), dtype=float32)


In [22]:
#indexing

x=tf.constant([0,1,1,1,2,3,7,8])

#the below just means print all but skip by 2, or whatever number you put after the semicolons
print(x[::2])

#you want to see just certain indices
temp=tf.constant([0,4,5])
print(tf.gather(x,temp))


tf.Tensor([0 1 2 7], shape=(4,), dtype=int32)
tf.Tensor([0 2 3], shape=(3,), dtype=int32)
